### ISSUE TITLE
[Enhancement] Implement Trident Enchantment

### ISSUE THREAD

**Issue by GooglePlugin** [Implasher/Aldous#4]
I noticed that you have implemented tridents in the software. It is better to have an enchantment effect on it.

**Comment by ZenTechnoDev** [comment]
Hi there. We will add it as soon as possible. But please do not hate us if we can't implement it because It's also a hard job to code it. But still, thank you for your suggestion

**Comment by Zadezter** [comment]
@ZenTechnoDev Trident is having a few problem with the entity. I'm not sure to add implement enchantment to Trident without to solve entity issue.
